version: '3.8'

services:
  employee:
    build: 
      context: .
      dockerfile: dockerfile.employee-service
    volumes:
      - .:/usr/src/app:rw
      - /usr/src/app/node_modules
    ports:
      - 8081:8080
    environment:
      - OTEL_LOG_LEVEL=ERROR
      - NODE_ENV=production
  auth:
    build: 
      context: .
      dockerfile: dockerfile.auth-service
    volumes:
      - .:/usr/src/app:rw
      - /usr/src/app/node_modules
    environment:
      - OTEL_LOG_LEVEL=ERROR
      - NODE_ENV=production
  prometheus:
      image: prom/prometheus
      command:
        - '--config.file=/etc/prometheus/prometheus.yml'
      volumes:
        - ./prometheus/:/etc/prometheus/
      ports:
        - 9090:9090
  collector:
    image: otel/opentelemetry-collector-contrib:latest
    volumes: 
      - ./collector/collector.yml:/etc/otel-collector-config.yml
    command: ["--config=/etc/otel-collector-config.yml"]
    ports:
      - "4317:4317"
      - "4318:4318"
      - "8889:8889"
  yace:
    image: ghcr.io/nerdswords/yet-another-cloudwatch-exporter:v0.55.0
    restart: always
    expose: 
      - 8082
    volumes:
      - ./yace/yace-config.yaml:/tmp/config.yml
    command:
      - -listen-address=:8082
      - -config.file=/tmp/config.yml
