apiVersion: v1alpha1
sts-region: ap-southeast-2
discovery:
  jobs:
    - type: AWS/ApiGateway
      regions: [ap-southeast-2]
      roles:
        - roleArn: arn:aws:iam::788132149295:role/yace-cloudwatch-metrics
      period: 300
      length: 300
      metrics:
        - name: Count
          statistics: [SampleCount, Sum]
        - name: Latency
          statistics: [Sum]
        - name: 5xx
          statistics: [Sum]
    - type: AWS/EC2
      regions: [ap-southeast-2]
      roles:
        - roleArn: arn:aws:iam::788132149295:role/yace-cloudwatch-metrics
      period: 300
      length: 3600
      metrics:
        - name: CPUUtilization
          statistics: [ Sum, Average]
        - name: DiskReadBytes
          statistics: [ Sum ]
        - name: DiskWriteBytes
          statistics: [ Sum ]
        - name: CPUCreditUsage
          statistics: [ Sum ]
        - name: CPUCreditBalance
          statistics: [ Sum ]
        - name: CPUSurplusCreditBalance
          statistics: [ Sum ]
        - name: CPUSurplusCreditsCharged
          statistics: [ Sum ]
    - type: AWS/S3
      regions: [ap-south-1]
      roles:
        - roleArn: arn:aws:iam::788132149295:role/yace-cloudwatch-metrics
      period: 300
      length: 300
      metrics:
        - name: BucketSizeBytes
          statistics: [ Average]
        - name: NumberOfObjects
          statistics: [ Average ]
        - name: AllRequests
          statistics: [ Sum ]
        - name: GetRequests
          statistics: [ Sum ]
        - name: PutRequests
          statistics: [ Sum ]
        - name: BytesUploaded
          statistics: [ Average , Sum ]
        - name: ListRequests
          statistics: [ Sum ]
    - type: lambda
      regions: [ap-south-1]
      roles:
        - roleArn: arn:aws:iam::788132149295:role/yace-cloudwatch-metrics
      period: 300
      length: 3600
      enableMetricData: true
        - name: Duration
          statistics: [ Sum, Maximum, Minimum, Average ]
        - name: Invocations
          statistics: [ Sum ]
        - name: Errors
          statistics: [ Sum ]
